{u'results': [{u'D': u'NNE',
               u'F': u'12',
               u'FG': u'22',
               u'FX': u'12',
               u'N': u'',
               u'P': u'1012',
               u'R': u'0.0',
               u'RH': u'70',
               u'RTE': u'',
               u'SED': u'',
               u'SNC': u'',
               u'SND': u'',
               u'T': u'1.0',
               u'TD': u'-3.8',
               u'V': u'',
               u'W': u'',
               u'err': u'',
               u'id': u'1',
               u'link': u'http://en.vedur.is/WeatherServlet/weather/observations/areas/reykjavik/#group=100&station=1',
               u'name': u'Reykjav\xedk',
               u'time': u'2015-04-27 19:00:00',
               u'valid': u'1'}]}